version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "09:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 5
  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "monthly"
      time: "09:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 5
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "09:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 5
  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "monthly"
      time: "09:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 5
