spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taskflowpro
    username: taskflowuser
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  security:
    user:
      name: admin
      password: admin123
flyway:
  enabled: true