package com.taskflowpro.api.service;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.*;

import java.util.Optional;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;

@SpringBootTest
public class TeamServiceTest {

    @Autowired
    private TeamService teamService;

    @MockBean
    private TeamRepository teamRepository;

    @BeforeEach
    public void setUp() {
        // Setup any common state or mocks here if needed
    }

    @Test
    public void testFindById() {
        Long id = 1L;
        Team expectedTeam = new Team();
        expectedTeam.setId(id);
        when(teamRepository.findById(id)).thenReturn(Optional.of(expectedTeam));

        Team result = teamService.findById(id);

        assertEquals(expectedTeam, result);
    }

    @Test
    public void testSave() {
        Team teamToSave = new Team();
        Team savedTeam = new Team();
        savedTeam.setId(1L); // Assuming the ID is generated by the database

        when(teamRepository.save(teamToSave)).thenReturn(savedTeam);

        Team result = teamService.save(teamToSave);

        assertEquals(savedTeam, result);
    }

    @Test
    public void testDeleteById() {
        Long id = 1L;
        teamService.deleteById(id);

        verify(teamRepository, times(1)).deleteById(id);
    }
}